build_script:
  ci-build.cmd

before_test:
  - appveyor DownloadFile https://github.com/KhronosGroup/glslang/releases/download/master-tot/glslang-master-windows-x64-Release.zip -FileName glslangvalidator.zip
  - unzip glslangvalidator.zip
  - set PATH=%APPVEYOR_BUILD_FOLDER%\bin;%PATH%

test_script:
  - ci-test.cmd

artifacts:
  - path: bin\Packages\Release\*.nupkg
    name: nugetPackages

deploy:
  provider: NuGet
  server: https://www.myget.org/F/mellinoe/api/v2/package
  api_key:
    secure: 2THjR9L+JBB3MCjzjC9e9eEJ9drdpgV6J/Hqej2yydtT0hvqf3kZNxtoiGz91CG7
  skip_symbols: false
  symbol_server: https://www.myget.org/F/mellinoe/api/v2/package
  artifact: nugetPackages
