build_script:
  ci-build.cmd

artifacts:
  - path: bin\Packages\Release\*.nupkg
    name: nugetPackages

deploy:
  provider: NuGet
  server: https://www.myget.org/F/mellinoe/api/v2/package
  api_key:
    secure: 2THjR9L+JBB3MCjzjC9e9eEJ9drdpgV6J/Hqej2yydtT0hvqf3kZNxtoiGz91CG7
  skip_symbols: false
  symbol_server: https://www.myget.org/F/mellinoe/api/v2/package
  artifact: nugetPackages
